---
# file: site.yml
# This playbook includes the following three playbooks, which will do necessary
# initialization installation to make ubuntu more functional.

  - hosts: "{{ hosts }}"
    user: shawn
    gather_facts: no
    sudo: yes

    roles:
      # This playbook will install the necessary programs of ubuntu 12.04 that
      # does not need a deskop environment to run.
      - system_server_part
      # This playbook will install the necessary programs of ubuntu 12.04 that
      # does need a deskop environment to run.
      - system_desktop_part

# This playbook will initialize my personal configuration of the `/home`
# directory.
  - hosts: "{{ hosts }}"
    user: shawn
    gather_facts: no

    roles:
      - shawn_init
