---
# file: site.yml
# This playbook includes relevant playbooks, which will do necessary initial
# installation to make ubuntu more functional in a laptop desktop environment.

  - hosts: "{{ hosts }}"
    user: "{{ user }}"
    gather_facts: no
    sudo: yes

    roles:
      # This playbook will install the necessary programs of ubuntu 14.04 that
      # does not need a deskop environment to run.
      - server
      # This playbook will install the necessary programs of ubuntu 14.04 that
      # does need a deskop environment to run.
      - desktop
      # For laptop.
      - laptop

# This playbook will initialize customized configuration of the `/home`
# directory.
  - hosts: "{{ hosts }}"
    user: "{{ user }}"
    gather_facts: no

    roles:
      - setup_user_home
