---
- name: "Install prerequisite of tensorflow."
  apt: pkg={{ item }} state="present"
  with_items:
    - virtualenv

- name: "Install tensorflow using user scheme."
  sudo: no
  command: pip install https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.6.0-cp27-none-linux_x86_64.whl
