---
- name: "Install prerequisite of tensorflow."
  command: pip install {{ item }}
  with_items:
    - virtualenv

- name: "Install tensorflow using user scheme."
  sudo: no
  command: pip install --user https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.7.1-cp27-none-linux_x86_64.whl
