---
- name: "Create user {{ new_user }} if non-exist."
  user: name={{ user }}
        generate_ssh_key=yes
        system=yes
        password=5fMSR/aa05Grw
        groups=sudo
        shell=/bin/bash
