---

- name: "Install dependences of scikit."
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - python-dev
    - libatlas-dev
    - libatlas3gf-base

- name: "make sure that ATLAS is used to provide the implementation of the BLAS linear algebra routines:"
  command: update-alternatives --set libblas.so.3 /usr/lib/atlas-base/atlas/libblas.so.3

- name: "make sure that ATLAS is used to provide the implementation of the LAPACK linear algebra routines:"
  command: update-alternatives --set liblapack.so.3 /usr/lib/atlas-base/atlas/liblapack.so.3

- name: "Install scikit."
  command: pip install -U {{ item }}
  with_items:
    - numpy
    - matplotlib
    - scipy
    - setuptools
    - scikit-learn
    - seaborn # To make matplotlib better.
