---
- name: "Change the sources.list"
  copy: src="sources.list" dest="/etc/apt/sources.list" force=yes

- name: "Change and source.list.d"
  copy: src="sources.list.d/" dest="/etc/apt/sources.list.d" force=yes

- name: "Install apt-keys"
  copy: src="trusted.gpg" dest="/etc/apt/" force=yes

- name: "Update apt cache"
  apt: update_cache=yes
  tags:
    - update

- name: "Install aptitude"
  apt: pkg=aptitude state=present
  tags:
    - update

- name: "Upgrade system"
  apt: upgrade=yes
  tags:
    - update

# Install necessary softwares.
- name: "Install git"
  apt: pkg=git state=present

- name: "Install cscope"
  apt: pkg="cscope" state=present

- name: "Install ctags"
  apt: pkg="ctags" state=present

- name: "Install tmux"
  apt: pkg=tmux state=present

- name: "Install w3m"
  apt: pkg=w3m state=present

- name: "Install tree"
  apt: pkg=tree state=present

# For using minted for latex.
- name: "Install pygmentize"
  apt: pkg="python-pygments" state=present

- name: "Install bvi."
  apt: pkg=bvi state=present

- name: "Install octave."
  apt: pkg=octave state=present

- name: "Install nmon."
  apt: pkg=nmon state=present

- name: "Install unrar."
  apt: pkg=unrar state=present

- name: "Install dos2unix."
  apt: pkg=dos2unix state=present
